---
ID: "4aa39b79-01ec-42e3-a8e3-a8d3c387fd92"
Parent: "7bfaeb7a-000b-43d3-8116-80f24a925ce6"
Template: "7bfaeb7a-000b-43d3-8116-80f24a925ce6"
Path: /sitecore/templates/Feature/EspireDemo/Composites/Rendering Parameters/Carousel/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230725T042812Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\b6hiKrOdCH
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\b6hiKrOdCH
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "b60d9b10-1f8a-4534-b5a0-d08c38166b54"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\b6hiKrOdCH
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230725T042812Z
