---
ID: "ccf0e2eb-4b87-4376-a03a-06e89af6c5dd"
Parent: "539b706f-6b74-49e8-8e9e-5329f09744f6"
Template: "539b706f-6b74-49e8-8e9e-5329f09744f6"
Path: /sitecore/templates/Feature/Espire Accelerator/Espire Components/Rendering Parameters/Seperator/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ad8eb1a5-2b3e-4bf8-8394-14ddf9db6ca3"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\manoj.chopkar@espire.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240103T135715Z
