---
ID: "5b451ded-536f-4d93-b38e-0473c776d4a1"
Parent: "e22aa818-7c05-4461-ad16-6e655eef3a34"
Template: "e22aa818-7c05-4461-ad16-6e655eef3a34"
Path: /sitecore/templates/Feature/EspireDemo/PageContent/Banner Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {7A59538F-43BB-41A8-88F8-3A9ADC3D1B80}
    {E22AA818-7C05-4461-AD16-6E655EEF3A34}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230712T073430Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\raman.gupta@espire.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\raman.gupta@espire.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "da58c612-46a8-48e2-8e05-a62227cceedf"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\raman.gupta@espire.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230712T073554Z
