---
ID: "288466fc-7c5c-4dc1-bc26-d85e744c5e6f"
Parent: "5c85ef0d-167f-41c8-bfb0-8fbe0cd784f0"
Template: "5c85ef0d-167f-41c8-bfb0-8fbe0cd784f0"
Path: /sitecore/templates/Feature/Espire Accelerator/Espire Components/Link Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {37951AF9-AB50-49EC-AEC1-8415C7236A6C}
    {5C85EF0D-167F-41C8-BFB0-8FBE0CD784F0}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120621T071605Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "adc35c5e-011a-4cc2-8bba-e739b2cbdbc1"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\manoj.chopkar@espire.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240103T132839Z
