---
ID: "036e51f8-dbe1-4d86-aa43-1dab39b4f9c6"
Parent: "3c12d833-5a5c-4244-8b09-e9600ef188ef"
Template: "3c12d833-5a5c-4244-8b09-e9600ef188ef"
Path: /sitecore/templates/Feature/Espire Accelerator/Espire Components/Rendering Parameters/Link/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "3905b57c-d68a-4634-be0c-5fd0ede618e7"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\manoj.chopkar@espire.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240103T132836Z
