---
ID: "6631db2c-713c-4e3f-9ec6-74adaf0aa873"
Parent: "582db1da-3ba9-4a80-8572-c773ebf7f8d1"
Template: "582db1da-3ba9-4a80-8572-c773ebf7f8d1"
Path: /sitecore/templates/Feature/EspireDemo/Composites/Rendering Parameters/Tabs/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230718T112643Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\raman.gupta@espire.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\raman.gupta@espire.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "a042df14-0871-470b-ac09-ca0af3b6314a"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\raman.gupta@espire.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230718T114307Z
