---
ID: "e92508a1-8f35-4e8d-9701-b901e8d66458"
Parent: "da3bd107-c623-40f4-82a8-459e31382b2a"
Template: "da3bd107-c623-40f4-82a8-459e31382b2a"
Path: /sitecore/templates/Feature/Espire Accelerator/Espire Components/Rendering Parameters/Article Banner/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "24aa6dbf-7a53-474b-95a4-9c4fa24c007e"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\manoj.chopkar@espire.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240103T130833Z
