---
ID: "0dc95c5f-2d2f-4ceb-8522-cd895ea4c045"
Parent: "961bac43-e9d7-4cbb-9785-c4b0d8c36750"
Template: "961bac43-e9d7-4cbb-9785-c4b0d8c36750"
Path: /sitecore/templates/Feature/Espire Accelerator/Espire Components/Seperator Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {931096CD-160D-4772-86BF-2CCD393F8F8C}
    {961BAC43-E9D7-4CBB-9785-C4B0D8C36750}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120621T071605Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "21ac7895-e33c-4037-9bc1-d2bbba6d7be4"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\manoj.chopkar@espire.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240103T135717Z
