---
ID: "2d5c3b0a-6f48-45f6-aaf1-aede45f1d2ad"
Parent: "4e22c6fc-22c4-4a4c-bd47-26f38c145829"
Template: "1105b8f8-1e00-426b-bf1f-c840742d827b"
Path: /sitecore/content/GlobalUniversitySC/GlobalUniversity/Presentation/Page Designs/Default
SharedFields:
- ID: "0966b999-0d0e-4278-acc9-9da69d461fe6"
  Hint: PartialDesigns
  Value: "{3BFB339C-DAC0-41A0-8FE7-451303FA3570}|{5F09274E-7AFD-4BD5-814F-D6DFAD457664}"
- ID: "c7c26117-dbb1-42b2-ab5e-f7223845cca3"
  Hint: __Thumbnail
  Value: |
    <image mediaid="{17BC40AA-DA0A-46CE-BFF6-5C8B09E1B8A8}" />
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20231220T053614Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\raman.gupta@espire.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\raman.gupta@espire.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "a813cba5-5271-4cda-a69f-4dfcfa97c1f5"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\manoj.chopkar@espire.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240115T121740Z
