---
ID: "81986d47-be0c-4b4b-84f1-e17eea973c3c"
Parent: "94790538-b326-4c4b-b513-a590cd319b69"
Template: "94790538-b326-4c4b-b513-a590cd319b69"
Path: /sitecore/templates/Feature/Espire Accelerator/Espire Components/Rendering Parameters/Language Selector/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "f8c73a41-73b6-4ada-8b4f-8c91fffe53ed"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\manoj.chopkar@espire.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240103T132404Z
