---
ID: "d021db92-1ca8-439b-a418-65c7ab9dcdca"
Parent: "a12eb411-b96c-442c-bcd4-e8f5219765fb"
Template: "a12eb411-b96c-442c-bcd4-e8f5219765fb"
Path: /sitecore/templates/Feature/Espire Accelerator/Espire Components/Search Box Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {E2525E27-F133-4B6D-9472-3D91EEB18678}
    {A12EB411-B96C-442C-BCD4-E8F5219765FB}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120621T071605Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "cb7e6d50-d25c-4900-be53-cd6ff75c93e0"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\manoj.chopkar@espire.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240103T135342Z
