---
ID: "5416f808-bbbc-4a6f-80e5-39dd3e0956d2"
Parent: "5ea2077e-7863-4206-ba05-eb47eddfb07e"
Template: "5ea2077e-7863-4206-ba05-eb47eddfb07e"
Path: /sitecore/templates/Project/Global University/Rendering Parameters/CourseImage/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "00ba67bc-17a0-4f9e-bfbe-95cfd25effbf"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\manoj.chopkar@espire.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240201T104045Z
