---
ID: "34c41999-6c79-4e2d-8cf9-e03a91865007"
Parent: "62c0e4d9-8baa-435b-8075-9128ebe7c1d0"
Template: "62c0e4d9-8baa-435b-8075-9128ebe7c1d0"
Path: /sitecore/templates/Feature/Espire Accelerator/Espire Components/Rendering Parameters/Social Media Share/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "e3129fda-b794-492f-8652-5c60eacf0b35"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\manoj.chopkar@espire.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240103T140712Z
