---
ID: "966cc1d4-feb4-4ead-87ce-d491c7a91277"
Parent: "3e4810ac-3b7f-4236-8e9d-810127e8a129"
Template: "3e4810ac-3b7f-4236-8e9d-810127e8a129"
Path: /sitecore/templates/Feature/Espire Accelerator/Espire Components/Rendering Parameters/Social Media Feeds/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "a351a1a5-a5f6-4ad3-aeca-568474cb9f56"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\manoj.chopkar@espire.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240103T140143Z
