---
ID: "56fb70ae-f050-4551-8345-088974c909c9"
Parent: "ec93b7c5-f659-44b1-9a4a-7b1174423d61"
Template: "ec93b7c5-f659-44b1-9a4a-7b1174423d61"
Path: /sitecore/templates/Feature/Espire Accelerator/Espire Components/Rendering Parameters/Banner/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "e3d56ad6-2784-4c18-ba53-8b52a06b74e9"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\manoj.chopkar@espire.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240103T121748Z
