---
ID: "8bf75ea6-912f-4d85-a3bd-63b9ae3cf9d4"
Parent: "2f637ecf-4da8-42e7-b3d5-f52bcf72135b"
Template: "2f637ecf-4da8-42e7-b3d5-f52bcf72135b"
Path: /sitecore/templates/Feature/Espire Accelerator/Espire Components/Listing Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {008A8090-6655-4528-BBD0-5E3BAE59FE3A}
    {2F637ECF-4DA8-42E7-B3D5-F52BCF72135B}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120621T071605Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "eea5205b-dcdf-4f60-9773-a8bf8b957c63"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\manoj.chopkar@espire.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240103T133301Z
